CREATE DATABASE VENTAS;
USE VENTAS;

CREATE TABLE USUARIOS(
ID INT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR (45),
PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTOS(
ID INT,
PRODUCTO VARCHAR(45),
COSTO INT,
EXISTENCIA INT,
PRIMARY KEY (ID)
);

CREATE TABLE CLIENTE(
ID INT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR (45),
DIRECCION VARCHAR(45),
ESTADO VARCHAR(45),
PRIMARY KEY (ID)
);