CREATE DATABASE SANARATE;
USE SANARATE;

CREATE TABLE CIUDADANO(
ID INT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR (45),
DPI VARCHAR (45),
DIRECCION VARCHAR (45),
TIPO_CASA VARCHAR (45),
SERVICIOS VARCHAR (45),
INGRESOS_MENSUALES INT,
ORNATO INT,
PRIMARY KEY (ID)
);
SELECT*FROM CIUDADANO;
INSERT INTO CIUDADANO (
ID,
NOMBRE, 
APELLIDO, 
DPI, 
DIRECCION, 
TIPO_CASA,
SERVICIOS,
INGRESOS_MENSUALES,
ORNATO)
VALUES (
'050', 
'CARLOS', 
'ARANA', 
'3053 81052', 
'SANARATE',
'CONTEMPORANEA',
'EXTRAS',
'3600',
'50');